//! List of migrations for the current app.
//!
//! Generated by cot CLI 0.3.1 on 2025-05-30 19:51:34+00:00

pub mod m_0001_initial;
/// The list of migrations for current app.
pub const MIGRATIONS: &[&::cot::db::migrations::SyncDynMigration] = &[
    &m_0001_initial::Migration,
];
